# Generated by Django 6.0.6 on 2026-07-03 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_description_product_short_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100, verbose_name='Tên khách hàng')),
                ('rating', models.IntegerField(verbose_name='Đánh giá (sao)')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Nội dung nhận xét')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='products.product')),
            ],
            options={
                'verbose_name': 'Nhận xét',
                'verbose_name_plural': 'Nhận xét',
                'ordering': ['-created_at'],
            },
        ),
    ]
